import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {

    //variables
    in property <string> result: "";

    //Callbacks
    callback divide-income(string, string);

    background: #313e50;
    GridLayout {
        padding: 50px;
        spacing: 20px;

        Row {
            Text {
                text: "Beregn import køb";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
                color: white;
            }
        }

        Row {
            pris := LineEdit {
                horizontal-alignment: center;
                font-size: 14px;
                placeholder-text: "Enter number";
                height: 35px;
            }

            Text {
                text: "Pris uden fragt";
                font-size: 15px;
                color: white;
            }
        }

        Row {
            fragt := LineEdit {
                horizontal-alignment: center;
                font-size: 14px;
                placeholder-text: "Enter number";
                height: 35px;
            }

            Text {
                text: "Fragt pris";
                font-size: 15px;
                color: white;
            }
        }

        Row {
            Button {
                text: "Beregn";
                primary: true;
                height: 35px;
                clicked => {
                    divide-income(pris.text, fragt.text);
                }
            }
        }

        Row {
            VerticalBox {
                Rectangle {
                    height: 100px;
                    background: #f2f2f2;
                    Text {
                        color: black;
                        font-size: 16px;
                        font-weight: 500;
                        text: root.result;
                    }
                }
            }
        }
    }
}
